version: '3.4'

services:
  app:
    build:
      context: .
    volumes:
      - ./built:/opt/beabee-signup/built
      - ./src/migrations:/opt/beabee-signup/src/migrations
      - app_uploads:/opt/beabee-signup/uploads
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - TYPEORM_URL=postgres://beabee-signup:beabee-signup@db/beabee-signup
      - TYPEORM_MIGRATIONS_DIR=src/migrations/
    ports:
      - ${MAIN_PORT}:3000

  db:
    image: postgres:14.5
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=beabee-signup
      - POSTGRES_PASSWORD=beabee-signup
      - POSTGRES_DATABASE=beabee-signup

volumes:
  app_uploads:
  db_data:
